export TWILIO_API_KEY=<TWILIO_API_KEY>
export BLUE_SNAP_API=https://sandbox.bluesnap.com
export BLUE_SNAP_USER_NAME=<BLUE_SNAP_USER_NAME>
export BLUE_SNAP_PASSWORD=<BLUE_SNAP_PASSWORD>
export BLUE_SNAP_API_TEST_USER=https://sandbox.bluesnap.com
export BLUE_SNAP_USER_NAME_TEST_USER=<BLUE_SNAP_USER_NAME_TEST_USER>
export BLUE_SNAP_PASSWORD_TEST_USER=<BLUE_SNAP_PASSWORD_TEST_USER>
export SDK_DEBUG_LOG=true
